// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using market_api.Context;

namespace market_api.Migrations {
    [DbContext(typeof(Db))]
    [Migration("20211203020254_Market")]
    partial class Market {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("market_api.Models.Category", b => {
                b.Property<Guid>("CategoryId")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(36)
                    .HasColumnType("char(36)");

                b.Property<string>("Name")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.HasKey("CategoryId");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("market_api.Models.Product", b => {
                b.Property<Guid>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(36)
                    .HasColumnType("char(36)");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("char(36)");

                b.Property<string>("Description")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<decimal>("Price")
                    .HasPrecision(20, 2)
                    .HasColumnType("decimal(20,2)");

                b.Property<DateTime>("Time")
                    .HasColumnType("datetime(6)");

                b.HasKey("ProductId");

                b.HasIndex("CategoryId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("market_api.Models.Product", b => {
                b.HasOne("market_api.Models.Category", null)
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
